import 'bootstrap/dist/css/bootstrap.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from './components/top-nav/page';
import BottomNav from './components/bottom-nav/page';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}> <TopNav />{children}<BottomNav /></body>
      
    </html>
  );
}
